[build]
  command = "CI=false NEXT_DISABLE_ESLINT=true npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000
  port = 8888
  publish = "public"